Repository bestdevhyo1225/large-system-design, pull requests merged in 2022-12, with the labels that each got.

#166 [PR] Post Redis 도메인 리팩토링
  sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreatePostUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisPipelineRepositoryImpl.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryImpl.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisService.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryTests.kt
Labels: refactor

#168 [PR] 타임라인 기능에 좋아요 횟수 포함해서 응답하도록 기능 추가
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/controller/PostController.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostTimelineUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishReadService.kt
Labels: enhancement

#169 [PR] Usecase 단위 테스트 코드 작성
  sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreatePostUsecase.kt
  sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/dto/CreatePostUsecaseDto.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateFollowMemberUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreatePostUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateWishUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/UpdateMemberInfluencerUsecaseTests.kt
Labels: enhancement

#170 [PR] query-api 행위 검증 테스트 작성
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateFollowMemberUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreatePostUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateWishUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/UpdateMemberInfluencerUsecaseTests.kt
  sns-feed-service-v2/application/query-api/src/test/kotlin/com/hyoseok/usecase/FindPostUsecaseTests.kt
Labels: enhancement

#171 [PR] 타임라인 리팩토링
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostTimelineUsecase.kt
  sns-feed-service-v2/common/src/main/kotlin/com/hyoseok/util/PageByPosition.kt
  sns-feed-service-v2/common/src/test/kotlin/com/hyoseok/PageRequestByPositionTests.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/entity/Feed.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/repository/FeedRedisTransactionRepositoryImpl.kt
Labels: enhancement

#172 [PR] Follow 도메인 개발
  sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreatePostUsecase.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateFollowMemberUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreatePostUsecaseTests.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostTimelineUsecase.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/Follow.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/FollowCount.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowCountRepository.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepository.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepositoryImpl.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/service/FollowReadService.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/service/FollowService.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/follow/entity/FollowCountTests.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/follow/repository/FollowRepositoryTests.kt
Labels: enhancement

#173 [PR] query-api 모듈 리팩토링
  .github/workflows/pr-ktlint-check.yml
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostTimelineUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
  sns-feed-service-v2/application/query-api/src/test/kotlin/com/hyoseok/usecase/FindPostUsecaseTests.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/Follow.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/entity/Post.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/entity/Wish.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishReadService.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/service/FeedRedisReadService.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/wish/service/WishRedisReadService.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/wish/service/WishRedisReadServiceTests.kt
Labels: enhancement, refactor

#175 [PR] Post, Wish 도메인 리팩토링
  README.md
  sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreatePostUsecase.kt
  sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreateWishUsecase.kt
  sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/UpdateMemberInfluencerUsecase.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreatePostUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateWishUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/UpdateMemberInfluencerUsecaseTests.kt
  sns-feed-service-v2/application/event-worker/src/main/kotlin/com/hyoseok/listener/WishKafkaListener.kt
  sns-feed-service-v2/application/event-worker/src/main/kotlin/com/hyoseok/listener/WishKafkaListenerErrorHandler.kt
  sns-feed-service-v2/application/event-worker/src/main/kotlin/com/hyoseok/listener/dto/WishEventDto.kt
  sns-feed-service-v2/application/event-worker/src/main/resources/application.yml
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/controller/PostController.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/mapper/PostCacheDtoMapper.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/mapper/PostDtoMapper.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsTimelineUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/dto/FindPostWishUsecaseDto.kt
  sns-feed-service-v2/application/query-api/src/test/kotlin/com/hyoseok/usecase/FindPostUsecaseTests.kt
  sns-feed-service-v2/client/event-publisher/src/main/kotlin/com/hyoseok/wish/dto/WishEventDto.kt
  sns-feed-service-v2/client/event-publisher/src/main/kotlin/com/hyoseok/wish/producer/WishKafkaProducer.kt
  sns-feed-service-v2/client/event-publisher/src/main/kotlin/com/hyoseok/wish/producer/WishKafkaProducerCallback.kt
  sns-feed-service-v2/client/event-publisher/src/main/resources/config/custom-client-event-publisher.yml
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/FollowCount.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepositoryImpl.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/service/FollowReadService.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/member/entity/Member.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/member/service/MemberService.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/dto/PostDto.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/entity/Post.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/dto/WishDto.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/dto/WishEventLogDto.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/dto/WishGroupByPostIdDto.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/entity/Wish.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/entity/WishEventLog.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishEventLogReadRepositoryImpl.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishEventLogRepository.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishReadRepository.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishReadRepositoryImpl.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishRepository.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishEventLogService.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishReadService.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishService.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/follow/repository/FollowRepositoryTests.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/member/entity/MemberTests.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/member/repository/MemberRepositoryTests.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/wish/repository/WishEventLogRepositoryTests.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/wish/repository/WishReadRepositoryTests.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/wish/repository/WishRepositoryTests.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/wish/service/WishServiceTests.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/dto/PostCacheDto.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisPipelineRepositoryImpl.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepository.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryImpl.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisService.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisPipelineRepositoryTests.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryTests.kt
Labels: enhancement, refactor

#176 [PR] FindPostTimelineUsecase 리팩토링
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsTimelineUsecase.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/Follow.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/FollowCount.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepository.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepositoryImpl.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/service/FollowReadService.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/member/service/MemberReadService.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepository.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepositoryImpl.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/follow/repository/FollowRepositoryTests.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/post/repository/PostRepositoryTests.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/entity/Feed.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepository.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepositoryImpl.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryImpl.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryTests.kt
Labels: enhancement, refactor

#177 [PR] FindPostsUsecase 리팩토링
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
Labels: enhancement, refactor

#180 [PR] build.gradle.kts 수정
  build.gradle.kts
  sns-feed-service-v2/application/batch/build.gradle.kts
Labels: bug

#181 [PR] Wish 캐시를 Post 엔티티 wishCount 프로퍼티에 일괄 반영하는 Batch Job 개발
  .github/workflows/pr-build-and-test.yml
  docker/redis/docker-compose.yml
  sns-feed-service-v2/application/api/src/main/resources/application.yml
  sns-feed-service-v2/application/batch/build.gradle.kts
  sns-feed-service-v2/application/batch/src/main/kotlin/com/hyoseok/job/WishCountToPostBatchJobConfig.kt
  sns-feed-service-v2/application/batch/src/main/resources/application.yml
  sns-feed-service-v2/application/batch/src/test/kotlin/com/hyoseok/config/BatchConfig.kt
  sns-feed-service-v2/application/batch/src/test/kotlin/com/hyoseok/job/WishCountToPostBatchJobConfigTests.kt
  sns-feed-service-v2/application/batch/src/test/resources/application.yml
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/wish/repository/WishRedisRepository.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/wish/repository/WishRedisRepositoryImpl.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/config/RedisEmbbededServerConfig.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/wish/repository/WishRedisRepositoryTests.kt
Labels: enhancement

#183 [PR] Post 도메인 리팩토링
  sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreatePostUsecase.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreatePostUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateWishUsecaseTests.kt
  sns-feed-service-v2/application/batch/src/main/kotlin/com/hyoseok/job/PostToPostCacheBatchJobConfig.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/mapper/PostCacheDtoMapper.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/mapper/PostDtoMapper.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostUsecase.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/dto/PostDto.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/entity/Post.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/post/entity/PostTests.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/dto/PostCacheDto.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisPipelineRepositoryImpl.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisService.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisPipelineRepositoryTests.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisRepositoryTests.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryTests.kt
Labels: refactor

#184 [PR] Post Redis 도메인 리팩토링 및 Batch 수정
  sns-feed-service-v2/application/batch/src/main/kotlin/com/hyoseok/job/PostToPostCacheBatchJobConfig.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsTimelineUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/service/FeedRedisReadService.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepository.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepositoryImpl.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisService.kt
Labels: enhancement, refactor

#185 [PR] firstResult/maxResults specified with collection fetch; applying in memory 버그 수정
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepositoryImpl.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/post/repository/PostRepositoryTests.kt
Labels: bug

#188 [PR] Feed 캐시 만료 시간 삭제 및 FeedCache 이름 변경
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsTimelineUsecase.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/dto/FeedCacheDto.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/entity/FeedCache.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/repository/FeedRedisTransactionRepositoryImpl.kt
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/service/FeedRedisReadService.kt
  sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/feed/repository/FeedRedisRepositoryTests.kt
Labels: enhancement

#190 [PR] DB 조회 기능 삭제
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsTimelineUsecase.kt
Labels: enhancement

#191 [PR] INFLUENCER_MIN_LIMIT_COUNT 값 1,000,000 으로 수정
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/FollowCount.kt
Labels: enhancement

#192 [PR] 타임라인 새로고침 기능 개발
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/config/resilience4j/ratelimiter/RateLimiterConfig.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/config/resilience4j/ratelimiter/property/FindPostRefreshTimelineUsecaseProperty.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/controller/PostController.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsRefreshTimelineUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsTimelineUsecase.kt
  sns-feed-service-v2/application/query-api/src/main/resources/application.yml
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
Labels: enhancement

#193 [PR] 팬아웃 Push 로직 개선
  sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreatePostUsecase.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreatePostUsecaseTests.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/dto/FollowDto.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowCountReadRepositoryImpl.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepository.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepositoryImpl.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/service/FollowReadService.kt
  sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/follow/repository/FollowRepositoryTests.kt
Labels: enhancement

#194 [PR] 타임라인 새로고침 기능 수정
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateFollowMemberUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreatePostUsecaseTests.kt
  sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateWishUsecaseTests.kt
  sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsRefreshTimelineUsecase.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/member/dto/MemberDto.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/member/entity/Member.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/member/service/MemberReadService.kt
  sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/member/service/MemberService.kt
Labels: enhancement

#196 [PR] mget 메서드로 변경
  sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
Labels: enhancement
